name: Docker image build

on:
  push:
    branches: [main]
    paths: [lambda/**]
  pull_request:
    branches: [main]
    paths: [lambda/**]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: lambda
          push: false
          cache-from: |
            type=gha,scope=lambda
          cache-to: |
            type=gha,scope=lambda
